# Generated by Django 5.0.14 on 2026-05-25 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('file_status', models.CharField(choices=[('temp', 'Temporaire'), ('permanent', 'Permanent')], default='temp', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('extracted', 'Extrait'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('category', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('cotisation', 'Cotisation'), ('don', 'Don'), ('other', 'Autre')], default='achat', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_supplier', models.CharField(blank=True, max_length=255)),
                ('extracted_category', models.CharField(blank=True, choices=[('achat', 'Achat'), ('vente', 'Vente'), ('cotisation', 'Cotisation'), ('don', 'Don'), ('other', 'Autre')], max_length=20, null=True)),
                ('validated_date', models.DateField(blank=True, null=True)),
                ('validated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('validated_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('validated_supplier', models.CharField(blank=True, max_length=255)),
                ('validated_category', models.CharField(blank=True, choices=[('achat', 'Achat'), ('vente', 'Vente'), ('cotisation', 'Cotisation'), ('don', 'Don'), ('other', 'Autre')], max_length=20, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='compta.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
